// generated by scripts/gen/examples.mjs — do not edit (runs from packages/ui-examples)

import { Example } from "./examples/shared/example";

import ButtonGroup01Example from "./examples/button-group/button-group-01";
import MiscPrimitives01Example from "./examples/misc-primitives/misc-primitives-01";
import Alert01Example from "./examples/alert/alert-01";
import Empty01Example from "./examples/empty/empty-01";
import Skeleton01Example from "./examples/skeleton/skeleton-01";
import Spinner01Example from "./examples/spinner/spinner-01";
import Progress01Example from "./examples/progress/progress-01";
import MiscPrimitives02Example from "./examples/misc-primitives/misc-primitives-02";
import Toggle01Example from "./examples/toggle/toggle-01";
import ToggleGroup01Example from "./examples/toggle-group/toggle-group-01";
import Breadcrumb01Example from "./examples/breadcrumb/breadcrumb-01";
import Card01Example from "./examples/card/card-01";
import Separator01Example from "./examples/separator/separator-01";
import Table01Example from "./examples/table/table-01";
import Pagination01Example from "./examples/pagination/pagination-01";
import Bubble01Example from "./examples/bubble/bubble-01";
import Marker01Example from "./examples/marker/marker-01";
import Attachment01Example from "./examples/attachment/attachment-01";
import Item01Example from "./examples/item/item-01";
import AspectRatio01Example from "./examples/aspect-ratio/aspect-ratio-01";
import MiscPrimitives03Example from "./examples/misc-primitives/misc-primitives-03";
import Dialog01Example from "./examples/dialog/dialog-01";
import MiscOverlays01Example from "./examples/misc-overlays/misc-overlays-01";
import MiscOverlays02Example from "./examples/misc-overlays/misc-overlays-02";
import DropdownMenu01Example from "./examples/dropdown-menu/dropdown-menu-01";
import ContextMenu01Example from "./examples/context-menu/context-menu-01";
import Command01Example from "./examples/command/command-01";
import ConfirmDialog01Example from "./examples/confirm-dialog/confirm-dialog-01";
import NumberField01Example from "./examples/number-field/number-field-01";
import MiscForms01Example from "./examples/misc-forms/misc-forms-01";
import MiscForms02Example from "./examples/misc-forms/misc-forms-02";
import MiscForms03Example from "./examples/misc-forms/misc-forms-03";
import Slider01Example from "./examples/slider/slider-01";
import MiscForms04Example from "./examples/misc-forms/misc-forms-04";
import MiscForms05Example from "./examples/misc-forms/misc-forms-05";
import MiscForms06Example from "./examples/misc-forms/misc-forms-06";
import MiscForms07Example from "./examples/misc-forms/misc-forms-07";
import Label01Example from "./examples/label/label-01";
import Input01Example from "./examples/input/input-01";
import DatePicker01Example from "./examples/date-picker/date-picker-01";
import DateRangePicker01Example from "./examples/date-range-picker/date-range-picker-01";
import TimePicker01Example from "./examples/time-picker/time-picker-01";
import TimeRangePicker01Example from "./examples/time-range-picker/time-range-picker-01";
import DateTimePicker01Example from "./examples/date-time-picker/date-time-picker-01";
import DateTimeRangePicker01Example from "./examples/date-time-range-picker/date-time-range-picker-01";
import TimezoneSelect01Example from "./examples/timezone-select/timezone-select-01";
import MiniCalendar01Example from "./examples/mini-calendar/mini-calendar-01";
import RelativeDatePicker01Example from "./examples/relative-date-picker/relative-date-picker-01";
import DurationInput01Example from "./examples/duration-input/duration-input-01";
import DataGrid01Example from "./examples/data-grid/data-grid-01";
import DataGrid02Example from "./examples/data-grid/data-grid-02";
import RichTextEditor01Example from "./examples/rich-text-editor/rich-text-editor-01";
import CodeEditor01Example from "./examples/code-editor/code-editor-01";
import MarkdownEditor01Example from "./examples/markdown-editor/markdown-editor-01";
import MiscEditors01Example from "./examples/misc-editors/misc-editors-01";
import MiscEditors02Example from "./examples/misc-editors/misc-editors-02";
import JqlInput01Example from "./examples/jql-input/jql-input-01";
import Stepper01Example from "./examples/stepper/stepper-01";
import Timeline01Example from "./examples/timeline/timeline-01";
import TreeView01Example from "./examples/tree-view/tree-view-01";
import SortableList01Example from "./examples/sortable-list/sortable-list-01";
import Kanban01Example from "./examples/kanban/kanban-01";
import EventCalendar01Example from "./examples/event-calendar/event-calendar-01";
import Gantt01Example from "./examples/gantt/gantt-01";
import FileDropzone01Example from "./examples/file-dropzone/file-dropzone-01";
import DiffViewer01Example from "./examples/diff-viewer/diff-viewer-01";
import JsonViewer01Example from "./examples/json-viewer/json-viewer-01";
import CodeBlock01Example from "./examples/code-block/code-block-01";
import LogViewer01Example from "./examples/log-viewer/log-viewer-01";
import MiscChartsBlocks01Example from "./examples/misc-charts-blocks/misc-charts-blocks-01";
import MiscChartsBlocks02Example from "./examples/misc-charts-blocks/misc-charts-blocks-02";
import MiscChartsBlocks03Example from "./examples/misc-charts-blocks/misc-charts-blocks-03";
import MiscChartsBlocks04Example from "./examples/misc-charts-blocks/misc-charts-blocks-04";
import MiscChartsBlocks05Example from "./examples/misc-charts-blocks/misc-charts-blocks-05";
import MiscChartsBlocks06Example from "./examples/misc-charts-blocks/misc-charts-blocks-06";
import DashboardShell01Example from "./examples/dashboard-shell/dashboard-shell-01";
import DetailPanel01Example from "./examples/detail-panel/detail-panel-01";
import ListDetail01Example from "./examples/list-detail/list-detail-01";
import TablePage01Example from "./examples/table-page/table-page-01";
import SettingsSplit01Example from "./examples/settings-split/settings-split-01";
import WizardShell01Example from "./examples/wizard-shell/wizard-shell-01";
import RunTimeline01Example from "./examples/run-timeline/run-timeline-01";
import Scrollspy01Example from "./examples/scrollspy/scrollspy-01";

export type SectionId = "primitives" | "overlays" | "forms" | "dates" | "data" | "editors" | "products" | "charts";

export const SECTIONS: { id: SectionId; label: string; hint: string }[] = [
  { id: "primitives", label: "基础元素", hint: "原子与容器" },
  { id: "overlays", label: "浮层", hint: "弹窗与提示" },
  { id: "forms", label: "表单", hint: "输入与选择" },
  { id: "dates", label: "日期时间", hint: "日历与时长" },
  { id: "data", label: "数据", hint: "表格与列表" },
  { id: "editors", label: "编辑器", hint: "代码与文档" },
  { id: "products", label: "看板日历", hint: "流程与排期" },
  { id: "charts", label: "图表指标", hint: "可视化" },
];

/** One <Example> chrome block per shared example, in gallery order. */
export const SECTION_BODIES: Record<SectionId, () => JSX.Element> = {
  primitives: () => (
    <>
      <Example id="button" title="Button / ButtonGroup">
        <ButtonGroup01Example />
      </Example>
      <Example id="badge-avatar-kbd" title="Badge / Avatar / Kbd">
        <MiscPrimitives01Example />
      </Example>
      <Example id="alert-empty-skeleton-alert" title="Alert">
        <Alert01Example />
      </Example>
      <Example id="alert-empty-skeleton-empty" title="Empty">
        <Empty01Example />
      </Example>
      <Example id="alert-empty-skeleton-skeleton" title="Skeleton">
        <Skeleton01Example />
      </Example>
      <Example id="alert-empty-skeleton-spinner" title="Spinner">
        <Spinner01Example />
      </Example>
      <Example id="alert-empty-skeleton-progress" title="Progress">
        <Progress01Example />
      </Example>
      <Example id="tabs-accordion-collapsible" title="Tabs / Accordion / Collapsible">
        <MiscPrimitives02Example />
      </Example>
      <Example id="toggle-toggle" title="Toggle">
        <Toggle01Example />
      </Example>
      <Example id="toggle-toggle-group" title="ToggleGroup">
        <ToggleGroup01Example />
      </Example>
      <Example id="table-card-separator-breadcrumb" title="Breadcrumb">
        <Breadcrumb01Example />
      </Example>
      <Example id="table-card-separator-card" title="Card">
        <Card01Example />
      </Example>
      <Example id="table-card-separator-separator" title="Separator">
        <Separator01Example />
      </Example>
      <Example id="table-card-separator-table" title="Table">
        <Table01Example />
      </Example>
      <Example id="pagination" title="Pagination">
        <Pagination01Example />
      </Example>
      <Example id="chat-surface-bubble" title="Bubble">
        <Bubble01Example />
      </Example>
      <Example id="chat-surface-marker" title="Marker">
        <Marker01Example />
      </Example>
      <Example id="chat-surface-attachment" title="Attachment">
        <Attachment01Example />
      </Example>
      <Example id="chat-surface-item" title="Item">
        <Item01Example />
      </Example>
      <Example id="aspect-ratio" title="AspectRatio">
        <AspectRatio01Example />
      </Example>
      <Example id="scroll-resizable" title="ScrollArea / Resizable / InputGroup / Calendar / Message">
        <MiscPrimitives03Example />
      </Example>
    </>
  ),
  overlays: () => (
    <>
      <Example id="dialog" title="Dialog">
        <Dialog01Example />
      </Example>
      <Example id="sheet-drawer" title="Sheet / Drawer">
        <MiscOverlays01Example />
      </Example>
      <Example id="popover-tooltip-hover" title="Popover / Tooltip / HoverCard">
        <MiscOverlays02Example />
      </Example>
      <Example id="menus-dropdown-menu" title="DropdownMenu">
        <DropdownMenu01Example />
      </Example>
      <Example id="menus-context-menu" title="ContextMenu">
        <ContextMenu01Example />
      </Example>
      <Example id="command" title="Command">
        <Command01Example />
      </Example>
      <Example id="confirm-toast" title="ConfirmDialog / Toast">
        <ConfirmDialog01Example />
      </Example>
    </>
  ),
  forms: () => (
    <>
      <Example id="number-field" title="NumberField" hint="Plus/minus and typing">
        <NumberField01Example />
      </Example>
      <Example id="input" title="Input / Textarea">
        <MiscForms01Example />
      </Example>
      <Example id="checkbox-switch-radio" title="Checkbox / Switch / Radio">
        <MiscForms02Example />
      </Example>
      <Example id="select" title="Select / NativeSelect">
        <MiscForms03Example />
      </Example>
      <Example id="slider" title="Slider / SliderRange">
        <Slider01Example />
      </Example>
      <Example id="phone-password" title="Phone / Password / Currency / Copyable">
        <MiscForms04Example />
      </Example>
      <Example id="search-auto" title="SearchInput / Autocomplete">
        <MiscForms05Example />
      </Example>
      <Example id="tags-user-rating-color" title="TagInput / UserPicker / Rating / ColorPicker">
        <MiscForms06Example />
      </Example>
      <Example id="cascader-transfer" title="Cascader / Transfer">
        <MiscForms07Example />
      </Example>
      <Example id="field-label-label" title="Label">
        <Label01Example />
      </Example>
      <Example id="field-label-input" title="Input">
        <Input01Example />
      </Example>
    </>
  ),
  dates: () => (
    <>
      <Example id="date-picker" title="DatePicker">
        <DatePicker01Example />
      </Example>
      <Example id="date-range-picker" title="DateRangePicker">
        <DateRangePicker01Example />
      </Example>
      <Example id="time-picker" title="TimePicker">
        <TimePicker01Example />
      </Example>
      <Example id="time-range-picker" title="TimeRangePicker">
        <TimeRangePicker01Example />
      </Example>
      <Example id="date-time-picker" title="DateTimePicker" hint="One popover: calendar + time">
        <DateTimePicker01Example />
      </Example>
      <Example id="date-time-range-picker" title="DateTimeRangePicker" hint="Two DateTimePickers; allDay switches to a date range">
        <DateTimeRangePicker01Example />
      </Example>
      <Example id="timezone-select" title="TimezoneSelect" hint="Common zones first; type to search the rest">
        <TimezoneSelect01Example />
      </Example>
      <Example id="mini-calendar" title="MiniCalendar">
        <MiniCalendar01Example />
      </Example>
      <Example id="relative-date-picker" title="RelativeDatePicker">
        <RelativeDatePicker01Example />
      </Example>
      <Example id="duration-input" title="DurationInput" hint="Hours and minutes, not a text box">
        <DurationInput01Example />
      </Example>
    </>
  ),
  data: () => (
    <>
      <Example id="data-grid" title="DataGrid" hint="Sort cycles asc → desc → none">
        <DataGrid01Example />
      </Example>
      <Example id="data-grid-custom" title="DataGrid · custom cells" hint="Avatar, progress, badges, row expand, selection, CSV">
        <DataGrid02Example />
      </Example>
    </>
  ),
  editors: () => (
    <>
      <Example id="rich-text-editor" title="RichTextEditor" hint="Tiptap — toolbar is live">
        <RichTextEditor01Example />
      </Example>
      <Example id="code-editor" title="CodeEditor" hint="CodeMirror 6">
        <CodeEditor01Example />
      </Example>
      <Example id="markdown-editor" title="MarkdownEditor" hint="Left CodeMirror, right live GFM preview">
        <MarkdownEditor01Example />
      </Example>
      <Example id="diff-viewer" title="DiffViewer" hint="PR-style hunks, line numbers, unified/split">
        <MiscEditors01Example />
      </Example>
      <Example id="jira-wiki" title="JiraWiki" hint="Left markup, right live preview">
        <MiscEditors02Example />
      </Example>
      <Example id="jql-input" title="JqlInput" hint="CodeMirror JQL · type to complete fields">
        <JqlInput01Example />
      </Example>
    </>
  ),
  products: () => (
    <>
      <Example id="stepper" title="Stepper" hint="Vertical and horizontal">
        <Stepper01Example />
      </Example>
      <Example id="timeline" title="Timeline">
        <Timeline01Example />
      </Example>
      <Example id="tree-sortable-tree-view" title="TreeView">
        <TreeView01Example />
      </Example>
      <Example id="tree-sortable-sortable-list" title="SortableList">
        <SortableList01Example />
      </Example>
      <Example id="kanban" title="Kanban" hint="Drag between columns · click a card for Jira details">
        <Kanban01Example />
      </Example>
      <Example id="calendar-gantt-event-calendar" title="EventCalendar" hint="Drag days or hours to create · All day uses date range picker">
        <EventCalendar01Example />
      </Example>
      <Example id="calendar-gantt-gantt" title="Gantt" hint="Drag days or hours to create · All day uses date range picker">
        <Gantt01Example />
      </Example>
      <Example id="dropzone" title="FileDropzone">
        <FileDropzone01Example />
      </Example>
      <Example id="inspectors-diff-viewer" title="DiffViewer">
        <DiffViewer01Example />
      </Example>
      <Example id="inspectors-json-viewer" title="JsonViewer">
        <JsonViewer01Example />
      </Example>
      <Example id="inspectors-code-block" title="CodeBlock">
        <CodeBlock01Example />
      </Example>
      <Example id="inspectors-log-viewer" title="LogViewer">
        <LogViewer01Example />
      </Example>
    </>
  ),
  charts: () => (
    <>
      <Example id="page-header-filter" title="PageHeader / FilterBar">
        <MiscChartsBlocks01Example />
      </Example>
      <Example id="stats" title="StatCard / TrendCard / Sparkline / Gauge / ProgressRing">
        <MiscChartsBlocks02Example />
      </Example>
      <Example id="charts" title="Donut / StackedBar / Radar">
        <MiscChartsBlocks03Example />
      </Example>
      <Example id="badges" title="StatusBadge / SeverityChip / EnvBadge">
        <MiscChartsBlocks04Example />
      </Example>
      <Example id="feeds" title="ActivityFeed / NotificationCenter / CommentThread / TestStepList">
        <MiscChartsBlocks05Example />
      </Example>
      <Example id="inspect" title="DescriptionList / RequestInspector / Terminal / FileTree / AttachmentGallery">
        <MiscChartsBlocks06Example />
      </Example>
      <Example id="dashboard-shell" title="DashboardShell" hint="Scroll the chart column — the header and KPI strip stay; narrow the panel and the rail folds underneath">
        <DashboardShell01Example />
      </Example>
      <Example id="detail-panel" title="DetailPanel">
        <DetailPanel01Example />
      </Example>
      <Example id="list-detail" title="ListDetail" hint="Scroll either pane — the toolbar and the other pane stay put">
        <ListDetail01Example />
      </Example>
      <Example id="table-page" title="TablePage" hint="Scroll the table — the toolbar stays put; select rows — the bar floats over, it never pushes rows down">
        <TablePage01Example />
      </Example>
      <Example id="settings-split" title="SettingsSplit" hint="Scroll the sections — the nav highlight follows; the save bar never scrolls out of view">
        <SettingsSplit01Example />
      </Example>
      <Example id="wizard-shell" title="WizardShell" hint="Step 2 starts invalid — Next is disabled until the mapping is filled in">
        <WizardShell01Example />
      </Example>
      <Example id="run-timeline" title="RunTimeline">
        <RunTimeline01Example />
      </Example>
      <Example id="scrollspy" title="Scrollspy">
        <Scrollspy01Example />
      </Example>
    </>
  ),
};
