export const JIRA_WIKI_SAMPLE = [
  "h2. Expected Behavior",
  "",
  "Users manage bonded parts in LX with full lifecycle support and standard bonded part attributes (part number, effective dates, active flag, audit fields as applicable).",
  "",
  "MOCK UI: [^bonded-parts-prototype.html]",
  "",
  "h2. Acceptance Criteria",
  "",
  "URL: [https://wd-stg.teslamotors.com/warpgt/gt/warpglobaltrade]",
  "* UI supports: create, update, delete, and review bonded parts records.",
  "* UI supports: download bonded parts list to Excel.",
  "* UI supports: bulk upload to add, update, and delete records (per defined template and validation rules).",
  "* Search/filter by: Part Number, Active Flag, Effective From, Effective To.",
  "* Role/permission model aligns with existing LX Warp Trade maintenance patterns (confirm with PM if new roles are needed).",
  "",
  "h2. Validation",
  "",
  "* Create/update/review: bonded parts records can be managed end-to-end in the LX UI.",
  "* Excel download matches grid/filter selection; bulk upload succeeds for add/update/delete scenarios and surfaces validation errors clearly.",
  "* Search filters return expected subsets for Part Number, Active Flag, Effective From, Effective To.",
  "",
  "h3. Open Questions",
  "",
  "-pending UI mockup and review the implementation detail-",
  "",
  "how to manage the user permissions?",
  "",
  "From Coco:",
  "",
  "_Just talked to Hailin, it's better to have a separate role and permission for this UI because very limited people in China Trade team will have edit permission. This also prevents from trade team members from other regions accidentally modify the record in this UI._",
  "",
  "|Role|Role Owner Approval?|Permission|",
  "|WarpTradeBonedPartEdit|YES|Creation Delete Modification|",
  "|WarpTradeBonedPartView|YES|Read Only|",
  "",
  "You can put me, Hailin, and Elaine Xie (谢靜芳) as the role owner for approval.",
].join("\n")
