#!/usr/bin/env node
/**
 * Extract component contracts from @monkey-mini-app/ui source (TS AST + JSDoc)
 * and write packages/dsh/skills/monkey-mini-app/references/{catalog.md,contracts/*.md}
 * plus packages/ui/ai/catalog.json
 *
 * Each contract includes:
 *   - component props (expanded)
 *   - referenced / co-exported types with field tables
 *     (e.g. ActivityFeed → TimelineItem { id, title, … })
 *
 * Annotate components with:
 *   /** summary
 *    *  @when when to pick this
 *    *  @example <Foo />
 *    * /
 *
 * Usage: pnpm skill:gen
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import ts from "typescript"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, "..")
const uiRoot = path.join(root, "packages/ui")
const srcRoot = path.join(uiRoot, "src")
const skillRef = path.join(root, "packages/dsh/skills/monkey-mini-app/references")
const contractsDir = path.join(skillRef, "contracts")
const catalogMdPath = path.join(skillRef, "catalog.md")
const catalogJsonPath = path.join(uiRoot, "ai/catalog.json")

const SKIP_FILES = new Set([
  "date-chrome",
  "jira-wiki-parse",
  "jql-language",
  "export-csv",
  "cells",
  "column-meta",
])

/** Types we never expand (stdlib / react noise). */
const SKIP_TYPE_NAMES = new Set([
  "Array",
  "ReadonlyArray",
  "Promise",
  "Record",
  "Partial",
  "Required",
  "Pick",
  "Omit",
  "NonNullable",
  "Extract",
  "Exclude",
  "ReturnType",
  "Parameters",
  "Awaited",
  "Date",
  "String",
  "Number",
  "Boolean",
  "Function",
  "Object",
  "ReactNode",
  "ReactElement",
  "CSSProperties",
  "HTMLAttributes",
  "ButtonHTMLAttributes",
  "InputHTMLAttributes",
  "FormEvent",
  "ChangeEvent",
  "MouseEvent",
  "KeyboardEvent",
  "ComponentProps",
  "ComponentType",
  "FC",
  "Ref",
  "RefObject",
  "MutableRefObject",
  "Dispatch",
  "SetStateAction",
  "Key",
  // tanstack / external table noise — props already show ColumnDef<T>
  "ColumnDef",
  "AccessorFn",
  "ColumnDefTemplate",
  "AggregationFnOption",
  "FilterFnOption",
  "SortingFnOption",
  "ColumnMeta",
  "SortingState",
  "ColumnFiltersState",
  "RowSelectionState",
  "VisibilityState",
  "Table",
  "Column",
  "Row",
  "Cell",
  "Header",
])

const GENERATED_BANNER =
  "<!-- generated by scripts/generate-skill.mjs — do not edit -->\n"

function listIndexModules() {
  const indexPath = path.join(srcRoot, "index.ts")
  const text = fs.readFileSync(indexPath, "utf8")
  const modules = []
  const re = /export \* from "\.\/(composites|products|blocks)\/([^"]+)"/g
  let match
  while ((match = re.exec(text))) {
    const layer = match[1]
    const name = match[2]
    if (SKIP_FILES.has(name)) continue
    const base = path.join(srcRoot, layer, name)
    const file = [".tsx", ".ts"]
      .map((ext) => base + ext)
      .find((candidate) => fs.existsSync(candidate))
    if (!file) continue
    modules.push({ layer, name, file })
  }
  return modules
}

function createProgram(files) {
  const configPath = path.join(uiRoot, "tsconfig.json")
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
  const parsed = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    uiRoot
  )
  return ts.createProgram({
    rootNames: [...new Set([...parsed.fileNames, ...files])],
    options: parsed.options,
  })
}

function jsDocInfo(node) {
  const comments = ts.getJSDocCommentsAndTags(node)
  let summary = ""
  const examples = []
  let when = ""
  for (const comment of comments) {
    if (!ts.isJSDoc(comment)) continue
    const raw = comment.comment
    if (typeof raw === "string") summary = raw.trim()
    else if (Array.isArray(raw))
      summary = raw.map((p) => (typeof p === "string" ? p : p.text)).join("").trim()
    for (const tag of comment.tags ?? []) {
      const name = tag.tagName.text
      const body =
        typeof tag.comment === "string"
          ? tag.comment.trim()
          : Array.isArray(tag.comment)
            ? tag.comment.map((p) => (typeof p === "string" ? p : p.text)).join("").trim()
            : ""
      if (name === "example" && body) examples.push(body.replace(/^\n/, ""))
      if ((name === "when" || name === "ai") && body) when = body
    }
  }
  return { summary, examples, when }
}

function isComponentName(name) {
  return /^[A-Z]/.test(name)
}

function typeString(checker, type, node, { expandAlias = false } = {}) {
  if (expandAlias) {
    const text = aliasSourceText(type)
    if (text) return text.replace(/\s+/g, " ").trim()
  }
  return checker
    .typeToString(
      type,
      node,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope
    )
    .replace(/\s+/g, " ")
    .trim()
}

/** Prefer the original `type Foo = …` RHS from source — expands unions cleanly. */
function aliasSourceText(type) {
  const sym = type.aliasSymbol ?? type.symbol
  if (!sym) return null
  const decl = sym.declarations?.[0]
  if (decl && ts.isTypeAliasDeclaration(decl) && decl.type) {
    return decl.type.getText()
  }
  if (decl && ts.isInterfaceDeclaration(decl)) return null
  return null
}

function isOptionalSymbol(symbol, decl) {
  return (
    (symbol.flags & ts.SymbolFlags.Optional) !== 0 ||
    (decl && ts.isPropertySignature(decl) && !!decl.questionToken) ||
    (decl && ts.isPropertyDeclaration(decl) && !!decl.questionToken) ||
    (decl && ts.isParameter(decl) && !!decl.questionToken)
  )
}

function fieldsFromObjectType(checker, type, node) {
  const fields = []
  const target = type.getNonNullableType()
  // Skip primitives / callables with no useful props
  if (
    target.flags &
    (ts.TypeFlags.String |
      ts.TypeFlags.Number |
      ts.TypeFlags.Boolean |
      ts.TypeFlags.ESSymbol |
      ts.TypeFlags.Void |
      ts.TypeFlags.Null |
      ts.TypeFlags.Undefined |
      ts.TypeFlags.Never)
  ) {
    return fields
  }
  for (const symbol of target.getProperties()) {
    if (symbol.name.startsWith("__@") || symbol.name === "prototype") continue
    // filter noisy function prototype stuff
    if (["toString", "valueOf", "toLocaleString"].includes(symbol.name) && target.getProperties().length > 8)
      continue
    const decl = symbol.valueDeclaration ?? symbol.declarations?.[0]
    if (!decl) continue
    // Skip methods on React-ish bags
    const propType = checker.getTypeOfSymbolAtLocation(symbol, decl)
    if (propType.getCallSignatures?.().length && !propType.getProperties?.().length) {
      // keep callbacks like onChange — they appear as props, good
    }
    let doc = ""
    const docs = symbol.getDocumentationComment(checker)
    if (docs?.length) doc = docs.map((d) => d.text).join("").trim()
    fields.push({
      name: symbol.name,
      type: typeString(checker, propType, decl),
      optional: isOptionalSymbol(symbol, decl),
      doc,
      _type: propType,
      _node: decl,
    })
  }
  return fields.sort((a, b) => a.name.localeCompare(b.name))
}

function propsFromSignature(checker, declaration) {
  const sig = checker.getSignatureFromDeclaration(declaration)
  if (!sig) return { props: [], propType: null }
  const params = sig.getParameters()
  if (!params.length) return { props: [], propType: null }
  const propSym = params[0]
  const propType = checker.getTypeOfSymbolAtLocation(
    propSym,
    propSym.valueDeclaration ?? declaration
  )
  const props = fieldsFromObjectType(checker, propType, declaration).map(
    ({ _type, _node, ...rest }) => rest
  )
  return { props, propType, node: declaration }
}

/**
 * Unwrap Array / Promise / Readonly / union nullish to the object-ish core.
 */
function unwrapType(type) {
  let t = type.getNonNullableType()
  // union of T | null already handled; also T | undefined
  if (t.isUnion?.()) {
    const parts = t.types.filter(
      (x) =>
        !(x.flags & (ts.TypeFlags.Null | ts.TypeFlags.Undefined | ts.TypeFlags.Void))
    )
    if (parts.length === 1) t = parts[0]
  }
  // Array<T> / T[]
  if (checkerIsArrayLike(t)) {
    const args = t.typeArguments ?? t.resolvedTypeArguments
    if (args?.[0]) return unwrapType(args[0])
    const indexed = t.getNumberIndexType?.()
    if (indexed) return unwrapType(indexed)
  }
  // Promise<T>
  const ref = t.symbol?.name
  if ((ref === "Promise" || ref === "Readonly") && t.typeArguments?.[0]) {
    return unwrapType(t.typeArguments[0])
  }
  return t
}

function checkerIsArrayLike(type) {
  const name = type.symbol?.name ?? type.aliasSymbol?.name
  if (name === "Array" || name === "ReadonlyArray") return true
  if (type.flags & ts.TypeFlags.Object) {
    const obj = type
    if (obj.objectFlags & ts.ObjectFlags.Reference) {
      const tn = obj.target?.symbol?.name
      if (tn === "Array" || tn === "ReadonlyArray") return true
    }
  }
  return false
}

function typeAliasName(type) {
  return type.aliasSymbol?.name ?? type.symbol?.name ?? null
}

function shouldExpandName(name) {
  if (!name) return false
  if (SKIP_TYPE_NAMES.has(name)) return false
  if (!/^[A-Z]/.test(name)) return false
  // skip DOM / React namespaces
  if (name.startsWith("React") || name.startsWith("JSX")) return false
  if (name.endsWith("Event") && name !== "CalendarEvent") return false
  return true
}

/** Only expand types declared inside our package source. */
function isPackageUiType(type) {
  const sym = type.aliasSymbol ?? type.symbol
  if (!sym) return false
  const decls = sym.getDeclarations?.() ?? sym.declarations ?? []
  for (const d of decls) {
    const file = d.getSourceFile?.()?.fileName ?? ""
    if (file.includes(`${path.sep}packages${path.sep}ui${path.sep}src${path.sep}`))
      return true
    // also accept when running with forward slashes
    if (file.includes("/packages/ui/src/")) return true
  }
  return false
}

/**
 * Collect expandable named types starting from prop types + file exports.
 * BFS so nested KanbanCard → KanbanComment is included.
 */
function collectRelatedTypes(checker, seedTypes, max = 24) {
  const out = []
  const seen = new Set()
  const queue = []

  function enqueue(type, hintName) {
    if (!type || out.length + queue.length >= max) return
    const core = unwrapType(type)
    const name = hintName || typeAliasName(core) || typeAliasName(type)
    if (!shouldExpandName(name)) return
    if (seen.has(name)) return
    // Prefer package declarations; allow alias name from our package only
    if (!isPackageUiType(core) && !isPackageUiType(type)) return
    // must look like a struct (has properties) or a string/union alias we still want
    const fields = fieldsFromObjectType(checker, core, undefined)
    const isUnion =
      core.isUnion?.() &&
      core.types.every(
        (t) =>
          t.flags &
          (ts.TypeFlags.StringLiteral |
            ts.TypeFlags.NumberLiteral |
            ts.TypeFlags.BooleanLiteral |
            ts.TypeFlags.EnumLiteral |
            ts.TypeFlags.Undefined |
            ts.TypeFlags.Null |
            ts.TypeFlags.String |
            ts.TypeFlags.Number |
            ts.TypeFlags.Boolean)
      )
    if (!fields.length && !isUnion) {
      // alias to primitive or opaque — still record one-liner
      const text = typeString(checker, type.aliasSymbol ? type : core, undefined, {
        expandAlias: true,
      })
      if (text) {
        seen.add(name)
        out.push({ name, kind: "alias", text, fields: [] })
      }
      return
    }
    seen.add(name)
    queue.push({ name, core, fields, isUnion, original: type })
  }

  for (const t of seedTypes) enqueue(t)

  while (queue.length && out.length < max) {
    const item = queue.shift()
    if (item.isUnion) {
      out.push({
        name: item.name,
        kind: "union",
        text: typeString(
          checker,
          item.original?.aliasSymbol ? item.original : item.core,
          undefined,
          { expandAlias: true }
        ),
        fields: [],
      })
      continue
    }
    const cleanFields = item.fields.map(({ _type, _node, ...rest }) => rest)
    out.push({ name: item.name, kind: "object", fields: cleanFields, text: null })
    // nest: enqueue field types
    for (const f of item.fields) {
      if (f._type) enqueue(f._type)
    }
  }
  return out
}

function exportedTypesFromFile(checker, sourceFile) {
  const types = []
  for (const stmt of sourceFile.statements) {
    if (!hasExport(stmt)) continue
    if (ts.isTypeAliasDeclaration(stmt) && isComponentName(stmt.name.text)) {
      const type = checker.getTypeAtLocation(stmt)
      // For `type X = { ... }` getTypeAtLocation on the decl is the alias type
      const sym = checker.getSymbolAtLocation(stmt.name)
      const t = sym ? checker.getDeclaredTypeOfSymbol(sym) : type
      types.push(t)
    }
    if (ts.isInterfaceDeclaration(stmt) && isComponentName(stmt.name.text)) {
      const sym = checker.getSymbolAtLocation(stmt.name)
      if (sym) types.push(checker.getDeclaredTypeOfSymbol(sym))
    }
  }
  return types
}

function propTypesFromSignature(checker, declaration) {
  const sig = checker.getSignatureFromDeclaration(declaration)
  if (!sig) return []
  const params = sig.getParameters()
  if (!params.length) return []
  const propSym = params[0]
  const propType = checker.getTypeOfSymbolAtLocation(
    propSym,
    propSym.valueDeclaration ?? declaration
  )
  const seeds = [propType]
  for (const field of fieldsFromObjectType(checker, propType, declaration)) {
    if (field._type) seeds.push(field._type)
  }
  return seeds
}

function extractFromFile(program, module) {
  const sourceFile = program.getSourceFile(module.file)
  if (!sourceFile) return []
  const checker = program.getTypeChecker()
  const fileExportedTypes = exportedTypesFromFile(checker, sourceFile)
  const components = []

  function pushComponent(name, node, propsNode) {
    if (!isComponentName(name)) return
    const doc = jsDocInfo(node)
    let props = []
    let seeds = [...fileExportedTypes]
    const fn = propsNode && ts.isFunctionLike(propsNode) ? propsNode : ts.isFunctionLike(node) ? node : null
    if (fn) {
      const extracted = propsFromSignature(checker, fn)
      props = extracted.props
      seeds.push(...propTypesFromSignature(checker, fn))
    }
    // Don't treat the component's own inline props bag as a named type dump
    // unless it has an alias name like FooProps
    const related = collectRelatedTypes(checker, seeds).filter(
      (t) => t.name !== name && t.name !== `${name}Props`
    )

    components.push({
      name,
      layer: module.layer,
      file: path.relative(root, module.file),
      slug: kebab(name),
      module: module.name,
      summary: doc.summary,
      when: doc.when,
      examples: doc.examples,
      props,
      types: related,
    })
  }

  for (const stmt of sourceFile.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name && hasExport(stmt)) {
      pushComponent(stmt.name.text, stmt, stmt)
      continue
    }
    if (ts.isVariableStatement(stmt) && hasExport(stmt)) {
      for (const decl of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(decl.name)) continue
        const init = decl.initializer
        if (!init) continue
        if (
          ts.isArrowFunction(init) ||
          ts.isFunctionExpression(init) ||
          ts.isCallExpression(init)
        ) {
          const fn =
            ts.isCallExpression(init) &&
            init.arguments[0] &&
            (ts.isArrowFunction(init.arguments[0]) ||
              ts.isFunctionExpression(init.arguments[0]))
              ? init.arguments[0]
              : ts.isArrowFunction(init) || ts.isFunctionExpression(init)
                ? init
                : null
          if (fn) pushComponent(decl.name.text, stmt, fn)
          else if (isComponentName(decl.name.text))
            pushComponent(decl.name.text, stmt, null)
        }
      }
    }
  }
  return components
}

function hasExport(node) {
  return !!node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
}

function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase()
}

function esc(s) {
  return String(s).replace(/\|/g, "\\|")
}

function renderFieldsTable(fields) {
  const lines = [
    "| field | type | required | note |",
    "|---|---|:---:|---|",
  ]
  for (const f of fields) {
    // checked = required; empty = optional (saves tokens, still scannable)
    lines.push(
      `| \`${f.name}\` | \`${esc(f.type)}\` | ${f.optional ? "" : "✓"} | ${esc(f.doc || "")} |`
    )
  }
  return lines
}

function renderContract(c) {
  const lines = [GENERATED_BANNER, `# ${c.name}`, ""]
  if (c.summary) lines.push(c.summary, "")
  if (c.when) lines.push(`**when** ${c.when}`, "")

  const typeImports = c.types.map((t) => t.name)
  const importNames = [c.name, ...typeImports].filter(
    (v, i, a) => a.indexOf(v) === i
  )
  lines.push(`\`import { ${importNames.join(", ")} } from "@monkey-mini-app/ui"\``, "")
  lines.push(`\`${c.file}\` · ${c.layer}`, "")

  if (c.props.length) {
    lines.push("## Props", "")
    lines.push(...renderFieldsTable(c.props), "")
  } else {
    lines.push("_Props not inferred — open source or pass standard React props._", "")
  }

  if (c.types?.length) {
    lines.push("## Types", "")
    for (const t of c.types) {
      lines.push(`### \`${t.name}\``, "")
      if (t.kind === "alias" || t.kind === "union") {
        // outside tables — do not escape | (that is only for md table cells)
        lines.push("```ts", t.text, "```", "")
      } else if (t.fields.length) {
        lines.push(...renderFieldsTable(t.fields), "")
      }
    }
  }

  if (c.examples.length) {
    lines.push("## Example", "")
    for (const ex of c.examples) {
      const body = ex.startsWith("```") ? ex : "```tsx\n" + ex + "\n```"
      lines.push(body, "")
    }
  }

  return lines.join("\n").trimEnd() + "\n"
}

function renderCatalog(components) {
  const byLayer = { composites: [], products: [], blocks: [] }
  for (const c of components) byLayer[c.layer]?.push(c)
  for (const list of Object.values(byLayer))
    list.sort((a, b) => a.name.localeCompare(b.name))

  const lines = [
    GENERATED_BANNER,
    "# @monkey-mini-app/ui catalog",
    "",
    "Import from `@monkey-mini-app/ui`. Host loads `@monkey-mini-app/ui/globals.css` + `UiProvider`.",
    "Open `contracts/<slug>.md` for **props + related types** + examples.",
    "",
  ]

  const sections = [
    ["blocks", "Layout & blocks"],
    ["products", "Products"],
    ["composites", "Composites (inputs)"],
  ]
  for (const [key, title] of sections) {
    lines.push(`## ${title}`, "")
    lines.push("| component | when | types | contract |")
    lines.push("|---|---|---|---|")
    for (const c of byLayer[key]) {
      const when = (c.when || c.summary || "—").replace(/\|/g, "\\|")
      const types =
        c.types?.length > 0
          ? c.types
              .slice(0, 4)
              .map((t) => `\`${t.name}\``)
              .join(" ")
          : "—"
      lines.push(
        `| \`${c.name}\` | ${when} | ${types} | [docs](contracts/${c.slug}.md) |`
      )
    }
    lines.push("")
  }

  lines.push(
    "## L1 primitives",
    "",
    "Button, Input, Textarea, Select, Combobox, Checkbox, Switch, RadioGroup, Slider, Label, Field, Dialog, AlertDialog, Sheet, Drawer, Popover, Tooltip, DropdownMenu, ContextMenu, Tabs, Accordion, Card, Badge, Avatar, Breadcrumb, Pagination, Progress, Skeleton, Spinner, Empty, Alert, Separator, ScrollArea, Resizable, Sidebar, Command, Calendar, Table, Chart, Toast, …",
    "",
    "Use L1 to glue products. Prefer composites for dates/inputs.",
    ""
  )
  return lines.join("\n")
}

function renderCatalogJson(components) {
  const group = (layer) =>
    [...new Set(components.filter((c) => c.layer === layer).map((c) => c.name))].sort()
  return {
    package: "@monkey-mini-app/ui",
    css: "@monkey-mini-app/ui/globals.css",
    import: 'import { Button, DataGrid, DatePicker, UiProvider } from "@monkey-mini-app/ui"',
    generated: true,
    composites: group("composites"),
    products: group("products"),
    blocks: group("blocks"),
    primitives: [
      "Button",
      "Input",
      "Select",
      "Dialog",
      "Sheet",
      "Tabs",
      "Table",
      "Card",
      "Badge",
      "Sidebar",
      "Tooltip",
      "Resizable",
      "ScrollArea",
    ],
  }
}

function main() {
  const modules = listIndexModules()
  const program = createProgram(modules.map((m) => m.file))
  const components = []
  for (const mod of modules) {
    components.push(...extractFromFile(program, mod))
  }

  const seen = new Set()
  const unique = []
  for (const c of components) {
    if (seen.has(c.name)) continue
    seen.add(c.name)
    unique.push(c)
  }

  fs.mkdirSync(contractsDir, { recursive: true })
  for (const file of fs.readdirSync(contractsDir)) {
    if (file.endsWith(".md")) fs.unlinkSync(path.join(contractsDir, file))
  }

  for (const c of unique) {
    fs.writeFileSync(path.join(contractsDir, `${c.slug}.md`), renderContract(c))
  }
  fs.writeFileSync(catalogMdPath, renderCatalog(unique))
  fs.mkdirSync(path.dirname(catalogJsonPath), { recursive: true })
  fs.writeFileSync(
    catalogJsonPath,
    JSON.stringify(renderCatalogJson(unique), null, 2) + "\n"
  )

  const withTypes = unique.filter((c) => c.types?.length).length
  console.log(
    `monkey-mini-app-ui skill: ${unique.length} contracts (${withTypes} with related types) → skills/monkey-mini-app-ui/references/contracts/`
  )
}

main()
